import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import QueryClientProvider from "@/modules/react-query/query-client-provider";
import { AuthProvider } from "@/modules/auth/provider";

const inter = Inter({
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={`${inter.className} h-full antialiased`}>
			<body className="min-h-full flex flex-col">
				<QueryClientProvider>
					<AuthProvider>{children}</AuthProvider>
				</QueryClientProvider>
			</body>
		</html>
	);
}
